# These are supported funding model platforms

github: [manzinello]
open_collective: mailgo
ko_fi: manzinello
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
