name: Run Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
